spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act?characterEncoding=UTF-8
    username: root
    password: Forever==2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


orign: gitdemotest

env: gitdemotest


girl: 
    name: meimei1
    age: 191